alias mv='mv -i'
alias cp='cp -i'
alias diff='git diff'
alias gcc='gcc -Wall -Wextra -Werror'
alias norminette='norminette -R CheckForbiddenSourceHeader'
alias 42FileChecker='bash ~/bin/42FileChecker/42FileChecker.sh --project libft --path ~/21-school/42/Libft/'
