alias mv='mv -i'
alias cp='cp -i'
alias ll='ls -la'
alias diffg='git diff'
alias youtube-dl-mkv='youtube-dl --merge-output-format mkv'
alias top='top -o cpu'
alias gccw='gcc -Wall -Wextra -Werror'
alias norminette='norminette -R CheckForbiddenSourceHeader'
